### ISSUE TITLE
Deduplicate: different file contents found in the following

### ISSUE THREAD

**Issue by Kabowyad** [aelve/codesearch#103]
When do `sbt web-server/assembly` then you get error
```[error] 1 error was encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /home/yan/.ivy2/cache/io.netty/netty-buffer/jars/netty-buffer-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-http/jars/netty-codec-http-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec/jars/netty-codec-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-resolver/jars/netty-resolver-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-handler/jars/netty-handler-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-socks/jars/netty-codec-socks-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-handler-proxy/jars/netty-handler-proxy-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport-native-epoll/jars/netty-transport-native-epoll-4.1.27.Final-linux-x86_64.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport-native-unix-common/jars/netty-transport-native-unix-common-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-resolver-dns/jars/netty-resolver-dns-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-dns/jars/netty-codec-dns-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:142)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:26)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:24)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:24)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:24)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:68)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:58)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (web-server/*:assembly) deduplicate: different file contents found in the following:
[error] /home/yan/.ivy2/cache/io.netty/netty-buffer/jars/netty-buffer-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-http/jars/netty-codec-http-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec/jars/netty-codec-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-resolver/jars/netty-resolver-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-handler/jars/netty-handler-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-socks/jars/netty-codec-socks-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-handler-proxy/jars/netty-handler-proxy-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport-native-epoll/jars/netty-transport-native-epoll-4.1.27.Final-linux-x86_64.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-transport-native-unix-common/jars/netty-transport-native-unix-common-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-resolver-dns/jars/netty-resolver-dns-4.1.27.Final.jar:META-INF/io.netty.versions.properties
[error] /home/yan/.ivy2/cache/io.netty/netty-codec-dns/jars/netty-codec-dns-4.1.27.Final.jar:META-INF/io.netty.versions.properties
```

**Comment by neongreen** [comment]
It was broken by https://github.com/aelve/codesearch/pull/97

**Comment by neongreen** [comment]
@Kabowyad please use three backticks for multiline code, not one
