### ISSUE TITLE
Null bytes in queries bring the server down

### ISSUE THREAD

**Issue by neongreen** [aelve/codesearch#240]
```
18:06:59.787 [application-akka.actor.default-dispatcher-200] DEBUG codesearch.core.search.Search - running CSEARCHINDEX=/index/cindex/.hackage_csearch_index csearch -n -f .*\.(hs-boot|hs|lhs|hsc|lhs-boot)$ /etc/passwd Data.List.HT
Exception in thread "Thread-436" java.io.IOException: invalid null character in command
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1024)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:144)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:117)
	at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:96)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
```

This is one of the last records in the web-server logs before it went down.

**Comment by neongreen** [comment]
Steps to reproduce:

```
curl "https://codesearch.aelve.com/haskell/search?query=%00%2Fetc%2Fpasswd&filter=Data.List.HT&insensitive=off&space=off&precise=off&sources=on"
```

**Comment by neongreen** [comment]
By the way: it does *not* die after I do it just once.

Open question: does it die if the %00 byte is sent several times? (to be tested locally)
