### ISSUE TITLE
Fix max_connections issues in Postgres

### ISSUE THREAD

**Issue by vlad107** [aelve/codesearch#59]

**Comment by neongreen** [comment]
This is how the issue looks like (for me it appears after I start the server locally and play with some queries):

```
00:16:34.277 [mydb connection adder] ERROR org.postgresql.Driver - Connection error:
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
        at org.postgresql.Driver$ConnectThread.getResult(Driver.java:403)
        at org.postgresql.Driver.connect(Driver.java:261)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:94)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:79)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by neongreen** [comment]
The easiest way to reproduce is to run this:

```
curl --silent -o/dev/null http://localhost:9000/haskell ; sleep 4

for n in `seq 1 60`; do echo "$n"; curl --silent -o/dev/null http://localhost:9000/haskell/search?query=module ; sleep 1; done
```

After about 50th try it goes into the "cannot acquire connection from data source" loop and seemingly never recovers.

**Comment by Som3** [comment]
Connection pool create for each `DefaultDB` implementation (4 hikariPool at now) - need move `val db = Database.forConfig("mydb")` into companion object - that fix it problem
